### ISSUE TITLE
Nutzersuche sehr strikt

### ISSUE THREAD

**Issue by chbaumgaertner** [n3phtys/ng-cervisia#3]
Hey,
bei der Suche nach Namen muss auf Sonderzeichen (Axons, ...) geachtet werden. Es wäre schön, wenn z.B. bei "Pálà" auch der Suchbegriff "Pala" funktionieren würde. 😁
Grüße von binär und Vall

**Comment by n3phtys** [comment]
Gute Idee, wurde so umgesetzt. Besser spät als nie.
